%% 1
%
% PL: Badanie zależności wymaganego 
% momentu obrotowego silnika 
% od promienia i współczynnika tarcia koła.
%
% ENG: Examination of electrical motor torque model in reference to wheel
% radius and friction coefficient
% 

%% INPUT PARAMETERS
%
% For given equation M_n > R*mu*N
% M_n - Torque, R - radius of wheel, mu - friction coef, N - pressure force
% generated by mass of robot
% 
% Let's analyze and plot dependencies
% 

M = 100;  % mas of robot "per wheel" in grams
g = 9810    % gravitational acceleration mm/s^2
% N = M * g;

mu = [0.01 :0.005: 0.5];    % coefs vector
R  = [5 :0.5: 50];            % radius coef

% mass of roboto depends on mass of wheels:
% M = M + C*R.^2
%C - constant coef
C = 0.001; % example value, in g/mm^2 unit


%% Calculations
%
X = zeros(99,91);
for k = 1 : length(mu)
    for m = 1 : length(R)
    X(k,m) =   mu(k)*R(m)*((M + C*R(m)*R(m))*g);      
    end
end



figure
subplot(1,2,1)
title('Minimal torque plot')
 
surf(R,mu,X)
shading('interp')
xlabel('Radius in [mm]');
ylabel('friction coef');
zlabel('Min Torque in [N*mm]')
view(0,90)

subplot(1,2,2)
surf(R,mu,X)
shading('interp')
xlabel('Radius in [mm]');
ylabel('friction coef');
zlabel('Min Torque in [N*mm]')
view(-145,-30)
