%% 3
%
% PL: Analiza danych z modelu czujnika odbiciowego w domenie czasowej i 
% częstotliwościowej. Zbadanie powstających artefaktów wprowadzanych  
% przez błędy konwersji A/C i C/A.
%
% ENG: Analysis of data generated by model of light sensor in time and
% frequency domain. Examination of artifacts added by A/D D/A conversion
% errors.
%
clc
clear all
% sinewave with magnitude and frequency modulation + noise
t = 0 : 0.01 : 2;
amp_mod = 0.5 : 0.005 : 1.5;
a = 0 : 0.005 : 1;
f_mod = 5 : 0.025 : 10;
f_mod1 = [ 10 : 0.1 : 0]
f_final = [f_mod f_mod1];
tmp1= randn(length(t),1)
tmp2= randn(length(t)+100,1);
tmp3= randn(length(t) + 320 ,1);
err = tmp1 + tmp2(101:100 + length(t)) + tmp3(321:320 + length(t));
ex = exp(amp_mod);

si = sin(f_mod.*t);
sens_out = ex.*si./4 + err'./6;
sens_out = sens_out.*(exp(-t));


figure
plot (t, sens_out)
xlabel('Time [s]')
ylabel('Sensor data value')
axis tight
title('Generated sensor dataset')

out_spec = fft(sens_out);
figure
plot([1:length(out_spec)/2], out_spec(1:length(out_spec)/2) )
axis tight
ylabel('Magnitude')
xlabel('Frequency [Hz]')
title('FFT of sample data')

%% Add higher freq than F_s plot FFT -> in conclusionADC
%
high_freq_signal = 0.2*sin(80*2*pi*t) + 0.3*sin(65*pi*2*t);
sens_out1 = sens_out + high_freq_signal;
out_spec = fft(sens_out1);
figure
plot([1:length(out_spec)/2], out_spec(1:length(out_spec)/2) )
axis tight
ylabel('Magnitude')
xlabel('Frequency [Hz]')
title('FFT of sample data')



%% simulate DAC conversion - ZOH
zoh = zeros(1,4*length(sens_out));

% 4 times higher output frequency

    for m = 1 : 1 : length(zoh)
        zoh(m) = sens_out(ceil(m/4));
    end



figure, plot([1:length(zoh)], zoh), title('Simulation of ZOH conversion')

out_spec = fft(sens_out);
figure
subplot(1,2,1)
plot([1:length(out_spec)/2], out_spec(1:length(out_spec)/2) )
axis tight
ylabel('Magnitude')
xlabel('Frequency [Hz]')
title('FFT of sample data')

out_spec = fft(zoh);
subplot(1,2,2)
plot([1:length(out_spec)/2], out_spec(1:length(out_spec)/2) )
axis tight
ylabel('Magnitude')
xlabel('Frequency [Hz]')
title('FFT of "ZOH"')



