%% 3
%
% PL: Analiza danych z modelu czujnika odbiciowego w domenie czasowej i 
% częstotliwościowej. Zbadanie powstających artefaktów wprowadzanych  
% przez błędy konwersji A/C i C/A.
%
% ENG: Analysis of data generated by model of light sensor in time and
% frequency domain. Examination of artifacts added by A/D D/A conversion
% errors.
%
clc
clear all
% modulowany sinus częstotliwościowo i amplitudowo + szum gaussowski
t = 0 : 0.01 : 2;
amp_mod = 0.5 : 0.005 : 1.5;
a = 0 : 0.005 : 1;
f_mod = 5 : 0.05 : 10;
f_mod1 = [ 10 : 0.1 : 0]
f_final = [f_mod f_mod1];
tmp1= wgn(length(t),1,0)
tmp2= wgn(length(t)+100,1,0);
tmp3= wgn(length(t) + 320 ,1, 0);
err = tmp1 + tmp2(101:100 + length(t)) + tmp3(321:320 + length(t));
ex = exp(amp_mod);

si = sin(f_mod.*t);
sens_out = ex.*si./4 + err'./6;

figure
plot (t,sens_out)
axis tight